//@version=5
indicator('EPIC STORSI', overlay=true)

// ------- Trading Style Presets
tradingStyle = input.string("Swing Trading", "Trading Style", options=["Scalping", "Swing Trading", "Position Trading"], tooltip="Choose your trading style preset")

// Initialize variables based on the selected style
var p = 21
var a = 21
var c = 30

if tradingStyle == "Scalping"
    p := 14
    a := 10
    c := 20
else if tradingStyle == "Position Trading"
    p := 50
    a := 30
    c := 50

// ------- User Customization for Colors and Thickness
userEpiclineColor = input.color(color.green, "Epicline Default Color")
userEpicMAColor = input.color(color.blue, "EpicMA Default Color")
userComboMAColor = input.color(color.yellow, "ComboMA Default Color")

EpiclineWidth = input.int(3, "Epicline Width", minval=1, maxval=5)
EpicMAWidth = input.int(3, "EpicMA Width", minval=1, maxval=5)
ComboMAWidth = input.int(2, "ComboMA Width", minval=1, maxval=5)

// ------- Indicator Calculations
UP = math.max(0, close - close[1])
DOWN = math.max(0, close[1] - close)

upMA = ta.sma(UP, p) / p
downMA = ta.sma(DOWN, p) / p

RS = upMA / downMA

// Compute the highest and lowest prices on p bars
hi = ta.highest(high, p)
lo = ta.lowest(low, p)

Epicline = (100 - 100 / (1 + RS) + (close - lo) / (hi - lo) * 100) / 2
EpicMA = ta.sma(Epicline, a)

Combo = (EpicMA + Epicline) / 2
ComboMA = ta.sma(Combo, c)

// ------- Plotting
plot(Epicline, color=userEpiclineColor, title='Epic STORSI', linewidth=EpiclineWidth)
plot(EpicMA, color=userEpicMAColor, title='EpicMA', linewidth=EpicMAWidth)
plot(ComboMA, color=userComboMAColor, title='Trigger', linewidth=ComboMAWidth)
